name: Scrap latest data

on:
  push:
  workflow_dispatch:
  schedule:
    # cada 4 horas
    - cron:  '5 */4 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: astral-sh/setup-uv@v3
    - name: Fetch latest data
      run: uv run --with-requirements requirements.txt scraper.py
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push